stages:
  - stage: Localize
    displayName: 'ODSP-Web Touchdown Localization'
    variables: 
    - group: VGtest
    jobs:
      - job: LocalizeOdspWeb
        displayName: 'Touchdown Localization (sans sp-client)'
        steps:
          - script: echo "Hello, ${{ variables.MySRT }}!"
            displayName: 'Print Hello World'
  
