stages:
  - stage: Localize
    displayName: 'ODSP-Web Touchdown Localization'
    jobs:
      - job: LocalizeOdspWeb
        displayName: 'Touchdown Localization (sans sp-client)'
        variables: 
          - template: es_variable_groups.yml      
        steps:
          - script: echo "Hello, ${{ variables.MySRT }}!"
            displayName: 'Print Hello World'
  
