stages:
  - stage: Localize
    displayName: 'ODSP-Web Touchdown Localization'
#    variables: 
#      - template: es_variable_groups.yml  
    jobs:
      - job: LocalizeOdspWeb
        displayName: 'Touchdown Localization (sans sp-client)'
        steps:
          - script: echo "Hello, ${{ variables.MySRT }}!"
            displayName: 'Print Hello World'
  
